### ISSUE TITLE
LICENSE file for SurfaceCtrl

### ISSUE THREAD

**Issue by ismail-yilmaz** [Xemuth/SurfaceCtrl#1]
Hello @Xemuth ,

I know we didn't yet publish the the docs for the structure of UppHub's nests (it is a todo), but root directory *should* have a license (in capitals) file. Could you copy (don't delete) the SurfaceCtrl/Copying file to the root directory as LICENSE? 

Thanks in advance and thank you for your efforts on developing this nice widget.

**Comment by Xemuth** [comment]
Hello @ismail-yilmaz, 

Ok done.
