### ISSUE TITLE
layout file path is wrong.

### ISSUE THREAD

**Issue by ismail-yilmaz** [Xemuth/SurfaceCtrl#3]
Hello xemuth,

As it happens, UppHub requires the file path to layout (lay) and image list (iml) file of examples be prepended with `examples/` 

E.g.

`#define LAYOUTFILE <examples/SurfaceCtrl_Demo/SurfaceCtrl_Demo.lay>`

**Comment by Xemuth** [comment]
Thanks @ismail-yilmaz  for your time.
It's now fixed.

Thanks again
